@startuml
actor User
collections Jira
control "KPM Sync" as App
collections KPM
User -> Jira: Transition status from "REJECTED" to "CLOSED"
Jira -> Jira: Set status "CLOSED"
App -> App: Detect Updated Status
alt KPM ticket accessible
    App -> App: Was not described?
else KPM ticket not accessible
    App -> Jira: Add comment "No access in KPM -> closed"
end
@enduml