@startuml
actor User
collections Jira
control "KPM Sync" as App
collections KPM
User -> Jira: Add question to field "Question to OEM"
note left
Is there a way to detect a new question?
Both ends are only pull based.
How do we identify if a question
was modified or if a new one was added?
end note
User -> Jira: Transition status to INFO MISSING
App -> App: Detect new question
App -> KPM: Create a new "Rueckfrage" (special feature or same as "Feedback from/to OEM?)
App -> KPM: Add the question to the "Rueckfrage" (Details required)
App -> KPM: Update KPM field "supplierresponse" with "DD.MM.YYYY: Rückfrage gestellt"
@enduml